### ISSUE TITLE
-c option/conflict bug

### ISSUE THREAD

**Issue by equwal** [Rouji/ffmpeg_distributed#1]
Putting `-c` in the ffmpeg arguments (even in a string) conflicts with the `-c` option that ffmpeg_distributed takes. This includes `-c:a` and `-c:v`. A workaround is to use `-acodec` or `-vcodec` instead.

**Comment by Rouji** [comment]
Not sure what you mean. The -c argument of the script should only change the behaviour of the ffmpeg processes producing intermediate files. 
Can you give an example?

**Comment by equwal** [comment]
```shell
$ ffmpeg_distributed.py -H <whatever> "myfile.mkv" "myfile-out.mkv" '-c:v libx265 -crf 18 -preset slow' '-c:a copy'
usage: ffmpeg_distributed.py [-h] [-s SEGMENT_LENGTH] -H HOST [-k] [-r] [-t TMP_DIR] [-c] input_file output_file remote_args concat_args
ffmpeg_distributed.py: error: argument -c/--copy-input: ignored explicit argument ':v libx265 -crf 18 -preset slow'
```

**Comment by equwal** [comment]
I think it is a bug in the shell argument processing

**Comment by Rouji** [comment]
That's expected behaviour... Just use -- to indicate end of options? It should parse everything following that as positional arguments

**Comment by equwal** [comment]
Hmm. My mistake, I forgot that shells work like this. Thanks for the help.
